const express = require("express");
const app = express();
const port = 3000; // You can choose any port you like

const cors = require("cors");

// Add this before defining your routes
app.use(cors());

// Define a GET route to fetch the data
app.get("/countryList", (req, res) => {
  res.json(countryList);
});
app.get("/countryDialingCodes", (req, res) => {
  res.json(countryDialingCodes);
});
app.get("/all", (req, res) => {
  res.json(ALL);
});

app.listen(port, () => {
  console.log(`Server is running on port ${port}`);
});

const countryList = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Côte d'Ivoire",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo (Congo-Brazzaville)",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czechia (Czech Republic)",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini (fmr. 'Swaziland')",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Holy See",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar (formerly Burma)",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine State",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States of America",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];
const countryDialingCodes = [
  "+93",
  "+355",
  "+213",
  "+376",
  "+244",
  "+1",
  "+54",
  "+374",
  "+61",
  "+43",
  "+994",
  "+1",
  "+973",
  "+880",
  "+1",
  "+375",
  "+32",
  "+501",
  "+229",
  "+975",
  "+591",
  "+387",
  "+267",
  "+55",
  "+673",
  "+359",
  "+226",
  "+257",
  "+225",
  "+238",
  "+855",
  "+237",
  "+1",
  "+236",
  "+235",
  "+56",
  "+86",
  "+57",
  "+269",
  "+242",
  "+506",
  "+385",
  "+53",
  "+357",
  "+420",
  "+243",
  "+45",
  "+253",
  "+1",
  "+1",
  "+593",
  "+20",
  "+503",
  "+240",
  "+291",
  "+372",
  "+268",
  "+251",
  "+679",
  "+358",
  "+33",
  "+241",
  "+220",
  "+995",
  "+49",
  "+233",
  "+30",
  "+1",
  "+502",
  "+224",
  "+245",
  "+592",
  "+509",
  "+379",
  "+504",
  "+36",
  "+354",
  "+91",
  "+62",
  "+98",
  "+964",
  "+353",
  "+972",
  "+39",
  "+1",
  "+81",
  "+962",
  "+7",
  "+254",
  "+686",
  "+965",
  "+996",
  "+856",
  "+371",
  "+961",
  "+266",
  "+231",
  "+218",
  "+423",
  "+370",
  "+352",
  "+261",
  "+265",
  "+60",
  "+960",
  "+223",
  "+356",
  "+692",
  "+222",
  "+230",
  "+52",
  "+691",
  "+373",
  "+377",
  "+976",
  "+382",
  "+212",
  "+258",
  "+95",
  "+264",
  "+674",
  "+977",
  "+31",
  "+64",
  "+505",
  "+227",
  "+234",
  "+850",
  "+389",
  "+47",
  "+968",
  "+92",
  "+680",
  "+970",
  "+507",
  "+675",
  "+595",
  "+51",
  "+63",
  "+48",
  "+351",
  "+974",
  "+40",
  "+7",
  "+250",
  "+1",
  "+1",
  "+1",
  "+685",
  "+378",
  "+239",
  "+966",
  "+221",
  "+381",
  "+248",
  "+232",
  "+65",
  "+421",
  "+386",
  "+677",
  "+252",
  "+27",
  "+82",
  "+211",
  "+34",
  "+94",
  "+249",
  "+597",
  "+268",
  "+46",
  "+41",
  "+963",
  "+992",
  "+255",
  "+66",
  "+670",
  "+228",
  "+676",
  "+1",
  "+216",
  "+90",
  "+993",
  "+688",
  "+256",
  "+380",
  "+971",
  "+44",
  "+1",
  "+598",
  "+998",
  "+678",
  "+58",
  "+84",
  "+967",
  "+260",
  "+263",
];


const ALL = [
  { countryName: "Afghanistan", countryCode: "+93" },
  { countryName: "Albania", countryCode: "+355" },
  { countryName: "Algeria", countryCode: "+213" },
  { countryName: "Andorra", countryCode: "+376" },
  { countryName: "Angola", countryCode: "+244" },
  { countryName: "Antigua and Barbuda", countryCode: "+1" },
  { countryName: "Argentina", countryCode: "+54" },
  { countryName: "Armenia", countryCode: "+374" },
  { countryName: "Australia", countryCode: "+61" },
  { countryName: "Austria", countryCode: "+43" },
  { countryName: "Azerbaijan", countryCode: "+994" },
  { countryName: "Bahamas", countryCode: "+1" },
  { countryName: "Bahrain", countryCode: "+973" },
  { countryName: "Bangladesh", countryCode: "+880" },
  { countryName: "Barbados", countryCode: "+1" },
  { countryName: "Belarus", countryCode: "+375" },
  { countryName: "Belgium", countryCode: "+32" },
  { countryName: "Belize", countryCode: "+501" },
  { countryName: "Benin", countryCode: "+229" },
  { countryName: "Bhutan", countryCode: "+975" },
  { countryName: "Bolivia", countryCode: "+591" },
  { countryName: "Bosnia and Herzegovina", countryCode: "+387" },
  { countryName: "Botswana", countryCode: "+267" },
  { countryName: "Brazil", countryCode: "+55" },
  { countryName: "Brunei", countryCode: "+673" },
  { countryName: "Bulgaria", countryCode: "+359" },
  { countryName: "Burkina Faso", countryCode: "+226" },
  { countryName: "Burundi", countryCode: "+257" },
  { countryName: "Côte d'Ivoire", countryCode: "+225" },
  { countryName: "Cabo Verde", countryCode: "+238" },
  { countryName: "Cambodia", countryCode: "+855" },
  { countryName: "Cameroon", countryCode: "+237" },
  { countryName: "Canada", countryCode: "+1" },
  { countryName: "Central African Republic", countryCode: "+236" },
  { countryName: "Chad", countryCode: "+235" },
  { countryName: "Chile", countryCode: "+56" },
  { countryName: "China", countryCode: "+86" },
  { countryName: "Colombia", countryCode: "+57" },
  { countryName: "Comoros", countryCode: "+269" },
  { countryName: "Congo (Congo-Brazzaville)", countryCode: "+242" },
  { countryName: "Costa Rica", countryCode: "+506" },
  { countryName: "Croatia", countryCode: "+385" },
  { countryName: "Cuba", countryCode: "+53" },
  { countryName: "Cyprus", countryCode: "+357" },
  { countryName: "Czechia (Czech Republic)", countryCode: "+420" },
  { countryName: "Democratic Republic of the Congo", countryCode: "+243" },
  { countryName: "Denmark", countryCode: "+45" },
  { countryName: "Djibouti", countryCode: "+253" },
  { countryName: "Dominica", countryCode: "+1" },
  { countryName: "Dominican Republic", countryCode: "+1" },
  { countryName: "Ecuador", countryCode: "+593" },
  { countryName: "Egypt", countryCode: "+20" },
  { countryName: "El Salvador", countryCode: "+503" },
  { countryName: "Equatorial Guinea", countryCode: "+240" },
  { countryName: "Eritrea", countryCode: "+291" },
  { countryName: "Estonia", countryCode: "+372" },
  { countryName: "Eswatini (fmr. 'Swaziland')", countryCode: "+268" },
  { countryName: "Ethiopia", countryCode: "+251" },
  { countryName: "Fiji", countryCode: "+679" },
  { countryName: "Finland", countryCode: "+358" },
  { countryName: "France", countryCode: "+33" },
  { countryName: "Gabon", countryCode: "+241" },
  { countryName: "Gambia", countryCode: "+220" },
  { countryName: "Georgia", countryCode: "+995" },
  { countryName: "Germany", countryCode: "+49" },
  { countryName: "Ghana", countryCode: "+233" },
  { countryName: "Greece", countryCode: "+30" },
  { countryName: "Grenada", countryCode: "+1" },
  { countryName: "Guatemala", countryCode: "+502" },
  { countryName: "Guinea", countryCode: "+224" },
  { countryName: "Guinea-Bissau", countryCode: "+245" },
  { countryName: "Guyana", countryCode: "+592" },
  { countryName: "Haiti", countryCode: "+509" },
  { countryName: "Holy See", countryCode: "+379" },
  { countryName: "Honduras", countryCode: "+504" },
  { countryName: "Hungary", countryCode: "+36" },
  { countryName: "Iceland", countryCode: "+354" },
  { countryName: "India", countryCode: "+91" },
  { countryName: "Indonesia", countryCode: "+62" },
  { countryName: "Iran", countryCode: "+98" },
  { countryName: "Iraq", countryCode: "+964" },
  { countryName: "Ireland", countryCode: "+353" },
  { countryName: "Israel", countryCode: "+972" },
  { countryName: "Italy", countryCode: "+39" },
  { countryName: "Jamaica", countryCode: "+1" },
  { countryName: "Japan", countryCode: "+81" },
  { countryName: "Jordan", countryCode: "+962" },
  { countryName: "Kazakhstan", countryCode: "+7" },
  { countryName: "Kenya", countryCode: "+254" },
  { countryName: "Kiribati", countryCode: "+686" },
  { countryName: "Kuwait", countryCode: "+965" },
  { countryName: "Kyrgyzstan", countryCode: "+996" },
  { countryName: "Laos", countryCode: "+856" },
  { countryName: "Latvia", countryCode: "+371" },
  { countryName: "Lebanon", countryCode: "+961" },
  { countryName: "Lesotho", countryCode: "+266" },
  { countryName: "Liberia", countryCode: "+231" },
  { countryName: "Libya", countryCode: "+218" },
  { countryName: "Liechtenstein", countryCode: "+423" },
  { countryName: "Lithuania", countryCode: "+370" },
  { countryName: "Luxembourg", countryCode: "+352" },
  { countryName: "Madagascar", countryCode: "+261" },
  { countryName: "Malawi", countryCode: "+265" },
  { countryName: "Malaysia", countryCode: "+60" },
  { countryName: "Maldives", countryCode: "+960" },
  { countryName: "Mali", countryCode: "+223" },
  { countryName: "Malta", countryCode: "+356" },
  { countryName: "Marshall Islands", countryCode: "+692" },
  { countryName: "Mauritania", countryCode: "+222" },
  { countryName: "Mauritius", countryCode: "+230" },
  { countryName: "Mexico", countryCode: "+52" },
  { countryName: "Micronesia", countryCode: "+691" },
  { countryName: "Moldova", countryCode: "+373" },
  { countryName: "Monaco", countryCode: "+377" },
  { countryName: "Mongolia", countryCode: "+976" },
  { countryName: "Montenegro", countryCode: "+382" },
  { countryName: "Morocco", countryCode: "+212" },
  { countryName: "Mozambique", countryCode: "+258" },
  { countryName: "Myanmar (formerly Burma)", countryCode: "+95" },
  { countryName: "Namibia", countryCode: "+264" },
  { countryName: "Nauru", countryCode: "+674" },
  { countryName: "Nepal", countryCode: "+977" },
  { countryName: "Netherlands", countryCode: "+31" },
  { countryName: "New Zealand", countryCode: "+64" },
  { countryName: "Nicaragua", countryCode: "+505" },
  { countryName: "Niger", countryCode: "+227" },
  { countryName: "Nigeria", countryCode: "+234" },
  { countryName: "North Korea", countryCode: "+850" },
  { countryName: "North Macedonia", countryCode: "+389" },
  { countryName: "Norway", countryCode: "+47" },
  { countryName: "Oman", countryCode: "+968" },
  { countryName: "Pakistan", countryCode: "+92" },
  { countryName: "Palau", countryCode: "+680" },
  { countryName: "Palestine State", countryCode: "+970" },
  { countryName: "Panama", countryCode: "+507" },
  { countryName: "Papua New Guinea", countryCode: "+675" },
  { countryName: "Paraguay", countryCode: "+595" },
  { countryName: "Peru", countryCode: "+51" },
  { countryName: "Philippines", countryCode: "+63" },
  { countryName: "Poland", countryCode: "+48" },
  { countryName: "Portugal", countryCode: "+351" },
  { countryName: "Qatar", countryCode: "+974" },
  { countryName: "Romania", countryCode: "+40" },
  { countryName: "Russia", countryCode: "+7" },
  { countryName: "Rwanda", countryCode: "+250" },
  { countryName: "Saint Kitts and Nevis", countryCode: "+1" },
  { countryName: "Saint Lucia", countryCode: "+1" },
  { countryName: "Saint Vincent and the Grenadines", countryCode: "+1" },
  { countryName: "Samoa", countryCode: "+685" },
  { countryName: "San Marino", countryCode: "+378" },
  { countryName: "Sao Tome and Principe", countryCode: "+239" },
  { countryName: "Saudi Arabia", countryCode: "+966" },
  { countryName: "Senegal", countryCode: "+221" },
  { countryName: "Serbia", countryCode: "+381" },
  { countryName: "Seychelles", countryCode: "+248" },
  { countryName: "Sierra Leone", countryCode: "+232" },
  { countryName: "Singapore", countryCode: "+65" },
  { countryName: "Slovakia", countryCode: "+421" },
  { countryName: "Slovenia", countryCode: "+386" },
  { countryName: "Solomon Islands", countryCode: "+677" },
  { countryName: "Somalia", countryCode: "+252" },
  { countryName: "South Africa", countryCode: "+27" },
  { countryName: "South Korea", countryCode: "+82" },
  { countryName: "South Sudan", countryCode: "+211" },
  { countryName: "Spain", countryCode: "+34" },
  { countryName: "Sri Lanka", countryCode: "+94" },
  { countryName: "Sudan", countryCode: "+249" },
  { countryName: "Suriname", countryCode: "+597" },
  { countryName: "Sweden", countryCode: "+46" },
  { countryName: "Switzerland", countryCode: "+41" },
  { countryName: "Syria", countryCode: "+963" },
  { countryName: "Tajikistan", countryCode: "+992" },
  { countryName: "Tanzania", countryCode: "+255" },
  { countryName: "Thailand", countryCode: "+66" },
  { countryName: "Timor-Leste", countryCode: "+670" },
  { countryName: "Togo", countryCode: "+228" },
  { countryName: "Tonga", countryCode: "+676" },
  { countryName: "Trinidad and Tobago", countryCode: "+1" },
  { countryName: "Tunisia", countryCode: "+216" },
  { countryName: "Turkey", countryCode: "+90" },
  { countryName: "Turkmenistan", countryCode: "+993" },
  { countryName: "Tuvalu", countryCode: "+688" },
  { countryName: "Uganda", countryCode: "+256" },
  { countryName: "Ukraine", countryCode: "+380" },
  { countryName: "United Arab Emirates", countryCode: "+971" },
  { countryName: "United Kingdom", countryCode: "+44" },
  { countryName: "United States of America", countryCode: "+1" },
  { countryName: "Uruguay", countryCode: "+598" },
  { countryName: "Uzbekistan", countryCode: "+998" },
  { countryName: "Vanuatu", countryCode: "+678" },
  { countryName: "Venezuela", countryCode: "+58" },
  { countryName: "Vietnam", countryCode: "+84" },
  { countryName: "Yemen", countryCode: "+967" },
  { countryName: "Zambia", countryCode: "+260" },
  { countryName: "Zimbabwe", countryCode: "+263" }
];
